<script>
// You can then call your custom JavaScript module using the syntax:
// <Vendor_Module>/js/filename.js, <Vendor_Module> mapping to view/frontend/web
  
// Defining 'Macademy_JsFun/js/fade-in-element' maps to:
// app/code/Macademy/JsFun/view/frontend/web/js/fade-in-element.js
require([
    'jquery',
    'Macademy_JsFun/js/fade-in-element'
], function(
    $,
    fadeInElement
) {
    'use strict';
    
    $(function() {
        // Arguments allow re-use and make the custom module composable.
        fadeInElement('.block-promo');
    });
});
</script>
