<div id="vue-test">
    <h1>{{ message }}</h1>
</div>

<script>
/**
 * Define the `require` statement inline of your PHTML template. RequireJS will automatically pull in
 * the required dependencies, and fire off your callback after they have resolved.
 */
require(['vue'], function(Vue) {
    'use strict'
    
    new Vue({
        el: '#vue-test',
        data: {
            message: 'This is a test'
        }
    });
});
</script>
