<?php
/**
 * The view model is then referenced by it's name and assigned to a variable, using PHP & Magento
 * naming conventions of camelCase for variable names. Also remember to typehint your view model.
 */

/** @var \Macademy\JsFun\ViewModel\Message $messageViewModel */
$messageViewModel = $block->getData('message_view_model');
?>

<div id="vue-test">
    <!-- The "message" property defined below is now available within your template. -->
    <h1>{{ message }}</h1>
</div>

<script type="text/x-magento-init">
    {
        "#vue-test": {
            "Macademy_JsFun/js/vue-test": {
                "message": "<?= $messageViewModel->getMessage() // Call your function here... ?>"
            }
        }
    }
</script>
